version: '3'

services:
  ajouteur_ligne:
    build: .
    depends_on:
      - web
    volumes:
      - web_data:/app
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - web_data:/usr/share/nginx/html

volumes:
  web_data: